version: '3'

services:
  labs:
    hostname: labs
    image: jaylenwang/timeloop-injection:latest
    ports:
      - "8888:8888"
    volumes:
      - ./workspace:/home/workspace
    environment:
      - USER_UID=501
      - USER_GID=501